from time import sleep

print("Hello 1")
print("Hello 2")
print("Hello 3")
print("Hello 4")
print("Hello 5")
print("Sleeping...")
sleep(3)
print("Hello 6")
print("Hello 7")
print("Hello 8")
print("Hello 9")
print("Hello 10")
print("Hello 11")
print("Hello 12")
print("Hello 13")
print("Hello 14")
print("Hello 15")
print("Hello 16")
print("Hello 17")
print("Hello 18")
print("Hello 19")
